/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    '[id]': typeof import('./src/components/[id].vue')['default']
    CareerSubjectCombineCharts: typeof import('./src/components/echarts/CareerSubjectCombineCharts.vue')['default']
    NAffix: typeof import('naive-ui')['NAffix']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NInput: typeof import('naive-ui')['NInput']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NSplit: typeof import('naive-ui')['NSplit']
    NTag: typeof import('naive-ui')['NTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    TheLinerChart: typeof import('./src/components/echarts/TheLinerChart.vue')['default']
    ThePersonCompareAffix: typeof import('./src/components/ThePersonCompareAffix.vue')['default']
    ThePersonCompareBord: typeof import('./src/components/ThePersonCompareBord.vue')['default']
    ThePersonRank: typeof import('./src/components/ThePersonRank.vue')['default']
    ThePersonSearch: typeof import('./src/components/ThePersonSearch.vue')['default']
    ThePersonTable: typeof import('./src/components/ThePersonTable.vue')['default']
    TheRadarChart: typeof import('./src/components/echarts/TheRadarChart.vue')['default']
  }
}
